experiment:
  name: augmentation_experiment
  description: Experiment to evaluate data augmentation techniques on model performance
  version: 1.0

# all paths are relatives to the home directory of the project SAM-Augmented_Ensemble-refactor
paths:
  # Path base dove si trovano i dataset (ex dataset_path = "../datasets/")
  dataset_root: "datasets/"

  # Dove salvare l'output (ex saving_path)
  output_root: "output/augmentation/"
  
  # Path dei checkpoint (ex checkpoints_root)
  checkpoints_root: "checkpoints_sam"

datasets:
  # List of datasets to use for training and testing
  folders:
    - "ProvaSmall/"
    #- "TrainDataset/"
    #- "small_ds/"
    #- "small_ds_2/"
    #- "TestDataset/CVC-300/"
    #- "TestDataset/CVC-ClinicDB/"
    #- "TestDataset/CVC-ColonDB/"
    #- "TestDataset/Kvasir/"
    #- "TestDataset/ETIS-LaribPolypDB/"

augmentation:
  #List of method names exactly as defined in lib.py
  methods:
    - "SAMAug"
    - "ourSAMAug"
    - "RG_segPrior"
    - "SV_segPrior"
    - "RG_logits"
    - "PCA_segPrior"

sam:
  # Choose [1], [2], or [1, 2]
  versions: [2]
  model_cfg: "sam2_hiera_l.yaml" # Choose the checkpoint file for the SAM model (ex: "sam_vit_h_4b8939.pth" or "sam2_hiera_large.pt")
  
  thresholds:
    crop_nms: 0.5
    box_nms: 0.5
    pred_iou: 0.5
  
  checkpoints:
    v1: "sam_vit_h_4b8939.pth"
    v2: "sam2_hiera_large.pt"

image_processing:
  # Parameters for image processing and augmentation
  resize_threshold: 2000 
  resize_dim: [1920, 1280] # Resize dimensions for images larger than the threshold
