experiment:
  name: clahe_lab_augmentation
  description: "CLAHE-LAB contrast enhancement"

paths:
  dataset_root: "datasets/"
  output_root: "output/augmentation/"      
  source_name: "original"

datasets:
  folders:
    - "ProvaSmall/"
    # - "TrainDataset/"
