experiment:
  name: "HSNet_Baseline_DA3"
  seed: 37

#all paths are relative to the location of Train.py file in src/models/HSNet/
paths:
  datasets_root: "../../../datasets/"
  offline_aug_base: "../../../output/augmentation/"   # folder DA offline (da1/da2/...)


  #------ TRAINING --------
  models_dir: "../../../output/models/"
  log_file: "train_log_hsnet_vanilla.log"

  #------TESTING ------
  prediction_dir: "../../../output/predictions/"
  logits_dir: "../../../output/logits/"

training:
  epochs: 100 #use 50 with lr method, 100 to compare with lr_method lrbase
  batchsize: 8 #20 with lr method, 8 to compare with lr_method lrbase
  trainsize: 352 # Original hardcoded image size for training

  size_rates: [0.75, 1.0, 1.25] # Multi-scale training (0.75x, 1.0x, 1.25x)
  clip_margin: 0.5 # Margin for gradient clipping

  decay_rate: 0.01
  decay_epochs: 50

  #create ensemble  diversity

  #da_source if da_method is da1 or da2, specify the source_name used in generation 
  augmentation: da3 # "da1", "da2", "da3" or null (no augmentation)
  da_source: "original"    #"original" for augmentation on the original dataset, choose other name for augmentation applied on already augmented dataset (e.g. SAMAug, ourSAMAug, RG_segPrior, SV_segPrior, RG_logits, PCA_segPrior)

  lr_method: lrbase   # "lra" | "lrb" | "lrc" | "lrbase" (uses the legacy optimizer/lr_schedule block)
  
  optimizer:
    type: "AdamW"
    lr: 0.00005 # Learning rate (5e-5)
    weight_decay: 0.0001 # Valore originale hardcoded (1e-4)

  lr_schedule:
    milestones: [15, 30] # Epochs at which to decay the learning rate
    decay_factor: 0.5 # Factor by which to decay the learning rate at each milestone

testing:
  test_checkpoint: "HSNet_Baseline_DA3.pth"
  testsize: 352

datasets:
  train: 
    - "TrainDataset"  #use only one folder for training divided in images and masks
  test:
    - "TestDatasets/CVC-300"
    - "TestDatasets/CVC-ClinicDB"
    - "TestDatasets/CVC-ColonDB"
    - "TestDatasets/Kvasir"
    - "TestDatasets/ETIS-LaribPolypDB"