experiment:
  name: "PolypPVT_Vanilla"
  seed: 37

# all paths are relative to the location of Train.py in src/models/PolypPVT/
paths:
  datasets_root: "../../../datasets/"

  # ------ TRAINING --------
  models_dir: "../../../output/models/"
  log_file: "train_log_polypvt_vanilla.log"

  # ------ TESTING ------
  prediction_dir: "../../../output/predictions/"
  logits_dir: "../../../output/logits/"

training:
  epochs: 150
  batchsize: 16
  trainsize: 352

  size_rates: [0.75, 1.0, 1.25]
  clip_margin: 0.5

  augmentation: 3 #da3

  optimizer:
    type: "AdamW"
    lr: 0.0001
    weight_decay: 0.0001

  lr_schedule:
    milestones: [15, 30] # Epochs at which to decay the learning rate
    decay_factor: 0.5 # Factor by which to decay the learning rate at each milestone


testing:
  test_checkpoint: "PolypPVT_Vanilla.pth"
  testsize: 352

datasets:
  train:
    - "TrainDataset"
  test:
    - "TestDatasets/TestDataset"
    #- "TestDatasets/CVC-300"
    #- "TestDatasets/CVC-ClinicDB"
    #- "TestDatasets/CVC-ColonDB"
    #- "TestDatasets/Kvasir"
    #- "TestDatasets/ETIS-LaribPolypDB"
