experiment:
  name: "PolypPVT_Aux_DA3"
  seed: 10

# all paths are relative to the location of Train.py in src/models/PolypPVT/
paths:
  datasets_root: "../../../datasets/"
  aux_root: "../../../output/augmentation/sam2/ourSAMAug/"  # subfolders must match datasets.train names

  # ------ TRAINING --------
  models_dir: "../../../output/models/"
  log_file: "train_log_polypvt_aux.log"

  # ------ TESTING ------
  prediction_dir: "../../../output/predictions/"

training:
  epochs: 100
  batchsize: 16
  trainsize: 352

  size_rates: [0.75, 1.0, 1.25]
  clip_margin: 0.5

  augmentation: "da3"

  optimizer:
    type: "AdamW"
    lr: 0.0001
    weight_decay: 0

  lr_schedule:
    milestones: [20]
    gamma: 0.2

testing:
  test_checkpoint: "PolypPVT_Aux_DA3.pth"
  testsize: 352

datasets:
  train:
    - "TrainDataset"
  test:
    - "TestDataset"
    #- "CVC-300"
    #- "CVC-ClinicDB"
    #- "CVC-ColonDB"
    #- "Kvasir"
    #- "ETIS-LaribPolypDB"
